version: 2.1

executors:
  default-executor:
    machine:
      image: ubuntu-2004:202010-01

jobs:
  build_and_test:
    executor: default-executor
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npm run test

  deploy:
    executor: default-executor
    steps:
      - checkout
      - run: echo "this is the deploy job"

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
