version: 2.1

executors:
  default-executor:
    machine:
      image: ubuntu-2004:202010-01

jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    executor: default-executor
    steps:
      - checkout
      - run: echo "this is the test job"

  deploy:
    executor: default-executor
    steps:
      - checkout
      - run: echo "this is the deploy job"

workflows:
  build_test_deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
